darknet_ros_topic: /darknet_ros/bounding_boxes
output_bbx3d_topic: /darknet_ros_3d/bounding_boxes
point_cloud_topic: /d435i/depth_registered/points
working_frame: t265_odom_frame  #d435i_link   
mininum_detection_thereshold: 0.3
minimum_probability: 0.3
interested_classes: ["person", "tvmonitor", "laptop", "chair", "sports ball", "cup", "vase", "keyboard", "mouse"]
